### PR TITLE
Changes to make it easier to replace or customize admin templates.

### PR DESCRIPTION
**Pull request by davidkellerman**
Added `admin-` prefix to `admin-theme-default/partials/head.ejs`, `admin-theme-default/partials/nav.ejs`, and `admin-theme-default/partials/scripts.ejs`. Changed references to `render()` instead of `include()`.

Changed `AdminController.js` to use generic names for element icons (rather than Font Awesome classes), then map them to class names in `admin-theme-default/partials/admin-nav-menu.ejs`. This leaves the `icon` option dangling, so added a hack to pass it as an `override` property for submenu items, then pick it up in `admin-nav-menu.ejs`.

### CODE REVIEW

**Comment by loppear** [comment]
Tested locally and made some changes, do these work for you @davidkellerman ?

 1. Needed to register the partials dir as templates for the `render` calls to work
 2. Changed the icon mapping to be a class property with ability to pass in overrides in opts, rather than the one `override` for legacy icon opt. Added the icon mapping lookup to a few missing places.

**Comment by davidkellerman** [comment]
@loppear Glad you caught the template dir registration. I "tested" the changes with my 100mhl code, rather than adding tests to the test suite.

I'm torn on the icon changes. Definitely catches the cases I left dangling. I really don't like that `AdminController` "knows" about the Font Awesome classes. In practical cases, overriding `iconClasses` isn't the whole story – you need to jigger the `.ejs` files to get the right resources loaded (e.g. other icon fonts, css) and probably tweak the html that's generated. You end up with an `iconClasses` patch _and_ `.ejs` changes, stuff spread all over.

Maybe a topic for a weekly/monthly meeting? I feel like our templating is broken; it's ugly to customize or move to new infrastructure. Gut feel is that it's too "low-level," and a layer of abstraction would be useful.

**Comment by loppear** [comment]
Agree on torn / wrong level of abstraction, just didn't feel like the 'implementation in an ejs partial with a legacy parameter' addressed it either.

**Comment by davidkellerman** [comment]
Me neither. I would have thrown it out entirely, but was afraid code somewhere would break.

**Comment by loppear** [comment]
Well, I approve this PR whether or not you revert e2fa543 and 045b5d6 then.

**Pull request merged**
